"""consultation persistence

Revision ID: 3d655fde5e1f
Revises: 
Create Date: 2026-05-28 16:27:17.755708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d655fde5e1f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consultations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('status', sa.Enum('LIVE', 'COMPLETED', 'REVIEWED', name='consultation_status'), nullable=False),
    sa.Column('patient_name', sa.String(length=160), nullable=True),
    sa.Column('patient_age', sa.Integer(), nullable=True),
    sa.Column('patient_pronouns', sa.String(length=32), nullable=True),
    sa.Column('patient_mrn', sa.String(length=64), nullable=True),
    sa.Column('patient_chief_complaint', sa.Text(), nullable=True),
    sa.Column('visit_date', sa.Date(), nullable=True),
    sa.Column('language', sa.String(length=16), nullable=True),
    sa.Column('deepgram_model', sa.String(length=64), nullable=True),
    sa.Column('openai_model_capable', sa.String(length=64), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_sec', sa.Integer(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_consultations'))
    )
    op.create_index(op.f('ix_consultations_user_id'), 'consultations', ['user_id'], unique=False)
    op.create_table('medications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('consultation_id', sa.UUID(), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('dose', sa.String(length=64), nullable=True),
    sa.Column('frequency', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['consultation_id'], ['consultations.id'], name=op.f('fk_medications_consultation_id_consultations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_medications')),
    sa.UniqueConstraint('consultation_id', 'external_id', name='uq_medications_consultation_id_external_id')
    )
    op.create_index(op.f('ix_medications_consultation_id'), 'medications', ['consultation_id'], unique=False)
    op.create_table('soap_sections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('consultation_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(length=2), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['consultation_id'], ['consultations.id'], name=op.f('fk_soap_sections_consultation_id_consultations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_soap_sections')),
    sa.UniqueConstraint('consultation_id', 'label', name='uq_soap_sections_consultation_id_label')
    )
    op.create_index(op.f('ix_soap_sections_consultation_id'), 'soap_sections', ['consultation_id'], unique=False)
    op.create_table('symptoms',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('consultation_id', sa.UUID(), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=160), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('duration', sa.String(length=64), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['consultation_id'], ['consultations.id'], name=op.f('fk_symptoms_consultation_id_consultations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_symptoms')),
    sa.UniqueConstraint('consultation_id', 'external_id', name='uq_symptoms_consultation_id_external_id')
    )
    op.create_index(op.f('ix_symptoms_consultation_id'), 'symptoms', ['consultation_id'], unique=False)
    op.create_table('timeline_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('consultation_id', sa.UUID(), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=False),
    sa.Column('timestamp_sec', sa.Float(), nullable=False),
    sa.Column('label', sa.String(length=160), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['consultation_id'], ['consultations.id'], name=op.f('fk_timeline_events_consultation_id_consultations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_timeline_events')),
    sa.UniqueConstraint('consultation_id', 'external_id', name='uq_timeline_events_consultation_id_external_id')
    )
    op.create_index(op.f('ix_timeline_events_consultation_id'), 'timeline_events', ['consultation_id'], unique=False)
    op.create_table('transcript_lines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('consultation_id', sa.UUID(), nullable=False),
    sa.Column('line_external_id', sa.String(length=64), nullable=False),
    sa.Column('timestamp_sec', sa.Float(), nullable=False),
    sa.Column('speaker', sa.String(length=16), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['consultation_id'], ['consultations.id'], name=op.f('fk_transcript_lines_consultation_id_consultations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transcript_lines'))
    )
    op.create_index(op.f('ix_transcript_lines_consultation_id'), 'transcript_lines', ['consultation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transcript_lines_consultation_id'), table_name='transcript_lines')
    op.drop_table('transcript_lines')
    op.drop_index(op.f('ix_timeline_events_consultation_id'), table_name='timeline_events')
    op.drop_table('timeline_events')
    op.drop_index(op.f('ix_symptoms_consultation_id'), table_name='symptoms')
    op.drop_table('symptoms')
    op.drop_index(op.f('ix_soap_sections_consultation_id'), table_name='soap_sections')
    op.drop_table('soap_sections')
    op.drop_index(op.f('ix_medications_consultation_id'), table_name='medications')
    op.drop_table('medications')
    op.drop_index(op.f('ix_consultations_user_id'), table_name='consultations')
    op.drop_table('consultations')
    # ### end Alembic commands ###
